services:
  strataone-api:
    build:
      context: .
    ports:
      - "${STRATAONE_API_PORT:-8080}:8080"
    environment:
      STRATAONE_BMC_USERNAME: ${STRATAONE_BMC_USERNAME:-}
      STRATAONE_BMC_PASSWORD: ${STRATAONE_BMC_PASSWORD:-}
      STRATAONE_CORS_ORIGINS: ${STRATAONE_CORS_ORIGINS:-http://localhost:8088,http://127.0.0.1:8088}
      STRATAONE_SEED_EXAMPLE: ${STRATAONE_SEED_EXAMPLE:-false}
      STRATAONE_AUTH_ENABLED: ${STRATAONE_AUTH_ENABLED:-true}
      STRATAONE_BOOTSTRAP_TOKEN: ${STRATAONE_BOOTSTRAP_TOKEN:-change-this-token}
      STRATAONE_API_TOKENS: ${STRATAONE_API_TOKENS:-}
      STRATAONE_EXECUTION_MODE: ${STRATAONE_EXECUTION_MODE:-inline}
      STRATAONE_ENABLE_LIVE_REDFISH: ${STRATAONE_ENABLE_LIVE_REDFISH:-false}
      STRATAONE_VAULT_PROVIDER: ${STRATAONE_VAULT_PROVIDER:-env}
      STRATAONE_VAULT_FILE: ${STRATAONE_VAULT_FILE:-}
      STRATAONE_VAULT_ADDR: ${STRATAONE_VAULT_ADDR:-}
      STRATAONE_VAULT_TOKEN: ${STRATAONE_VAULT_TOKEN:-}
      STRATAONE_VAULT_PATH: ${STRATAONE_VAULT_PATH:-secret/data/strataone}
    volumes:
      - ./.strataone:/app/.strataone

  strataone-dashboard:
    image: nginx:1.27-alpine
    ports:
      - "${STRATAONE_DASHBOARD_PORT:-8088}:80"
    volumes:
      - ./dashboard:/usr/share/nginx/html:ro
    depends_on:
      - strataone-api
