import json
import os
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from pydantic import BaseModel

from strataone.orchestrator import Orchestrator
from strataone.preflight import PreflightRunner
from strataone.state import PlatformType, SiteSpec


class ArtifactBundle(BaseModel):
    site_name: str
    output_dir: str
    files: list[str]


class ArtifactGenerator:
    def __init__(self, output_root: Path | None = None) -> None:
        self.output_root = output_root or Path(os.getenv("STRATAONE_ARTIFACT_DIR", ".strataone/artifacts"))

    def generate(self, spec: SiteSpec) -> ArtifactBundle:
        site_dir = self.output_root / spec.site.name
        site_dir.mkdir(parents=True, exist_ok=True)

        plan = Orchestrator().plan(spec).model_dump(mode="json")
        preflight = PreflightRunner().run(spec).model_dump(mode="json")
        files = {
            "manifest.json": self._manifest(spec),
            "deployment-plan.json": plan,
            "preflight-report.json": preflight,
            "network-summary.json": spec.network.model_dump(mode="json"),
            "site-spec.json": spec.model_dump(mode="json"),
        }

        if spec.platform.type == PlatformType.AZURE_LOCAL:
            files["azure-local.parameters.json"] = self._azure_local_parameters(spec)
            files["azure-local.bicep"] = self._azure_local_bicep(spec)
            files["terraform.tfvars.json"] = self._terraform_vars(spec)
            files["main.tf"] = self._terraform_main(spec)
            files["arc-registration.ps1"] = self._arc_registration_script(spec)
        files["ansible-inventory.yml"] = self._ansible_inventory(spec)
        files["ansible-playbook.yml"] = self._ansible_playbook(spec)

        written = []
        for name, payload in files.items():
            path = site_dir / name
            if isinstance(payload, str):
                path.write_text(payload, encoding="utf-8")
            else:
                path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
            written.append(str(path))

        return ArtifactBundle(site_name=spec.site.name, output_dir=str(site_dir), files=written)

    def _manifest(self, spec: SiteSpec) -> dict[str, Any]:
        return {
            "generated_at": datetime.now(UTC).isoformat(),
            "site_name": spec.site.name,
            "location": spec.site.location,
            "deployment_model": spec.site.deployment_model,
            "platform": spec.platform.type.value,
            "hardware_provider": spec.hardware.vendor,
            "nodes": [node.model_dump(mode="json") for node in spec.hardware.nodes],
        }

    def _azure_local_parameters(self, spec: SiteSpec) -> dict[str, Any]:
        azure = spec.platform.azure
        return {
            "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
            "contentVersion": "1.0.0.0",
            "parameters": {
                "clusterName": {"value": spec.platform.cluster_name or spec.site.name},
                "resourceGroup": {"value": azure.resource_group if azure else None},
                "location": {"value": azure.region if azure else None},
                "topology": {"value": spec.platform.topology},
                "nodes": {"value": [node.model_dump(mode="json") for node in spec.hardware.nodes]},
                "network": {"value": spec.network.model_dump(mode="json")},
            },
        }

    def _arc_registration_script(self, spec: SiteSpec) -> str:
        azure = spec.platform.azure
        tenant_line = f"$TenantId = \"{azure.tenant_id}\"" if azure and azure.tenant_id else "$TenantId = \"<tenant-id>\""
        subscription = azure.subscription_id if azure else "<subscription-id>"
        resource_group = azure.resource_group if azure else "<resource-group>"
        region = azure.region if azure else "<region>"
        return f"""# Generated by StrataOne for {spec.site.name}
# Review and replace placeholders before running in production.
$SubscriptionId = "{subscription}"
{tenant_line}
$ResourceGroup = "{resource_group}"
$Location = "{region}"

az login --tenant $TenantId
az account set --subscription $SubscriptionId
az group create --name $ResourceGroup --location $Location

# Azure Local Arc registration steps are intentionally left as reviewed operator actions.
# Add Microsoft-supported Azure Local registration commands for your target release here.
"""

    def _azure_local_bicep(self, spec: SiteSpec) -> str:
        azure = spec.platform.azure
        location = azure.region if azure else "westeurope"
        cluster_name = spec.platform.cluster_name or spec.site.name
        return f"""// Generated by StrataOne for {spec.site.name}
// Operator review required before production deployment.
targetScope = 'resourceGroup'

param location string = '{location}'
param clusterName string = '{cluster_name}'
param topology string = '{spec.platform.topology or "custom"}'

output deploymentContract object = {{
  clusterName: clusterName
  location: location
  topology: topology
  nodeCount: {len(spec.hardware.nodes)}
}}
"""

    def _terraform_vars(self, spec: SiteSpec) -> dict[str, Any]:
        azure = spec.platform.azure
        return {
            "site_name": spec.site.name,
            "cluster_name": spec.platform.cluster_name or spec.site.name,
            "platform": spec.platform.type.value,
            "location": azure.region if azure else spec.site.location,
            "resource_group": azure.resource_group if azure else f"rg-{spec.site.name}",
            "topology": spec.platform.topology,
            "nodes": [node.model_dump(mode="json") for node in spec.hardware.nodes],
            "network": spec.network.model_dump(mode="json"),
        }

    def _terraform_main(self, spec: SiteSpec) -> str:
        return f"""# Generated by StrataOne for {spec.site.name}
# This is an integration scaffold for provider-specific Terraform modules.

variable "site_name" {{ type = string }}
variable "cluster_name" {{ type = string }}
variable "platform" {{ type = string }}
variable "location" {{ type = string }}
variable "resource_group" {{ type = string }}
variable "topology" {{ type = string }}
variable "nodes" {{ type = any }}
variable "network" {{ type = any }}

output "strataone_deployment_contract" {{
  value = {{
    site_name      = var.site_name
    cluster_name   = var.cluster_name
    platform       = var.platform
    resource_group = var.resource_group
    topology       = var.topology
    node_count     = length(var.nodes)
  }}
}}
"""

    def _ansible_inventory(self, spec: SiteSpec) -> str:
        host_lines = "\n".join(
            f"      {node.serial}:\n        ansible_host: {node.bmc_ip}\n        role: {node.role}"
            for node in spec.hardware.nodes
        )
        return f"""all:
  children:
    strataone_nodes:
      hosts:
{host_lines}
      vars:
        strataone_site: {spec.site.name}
        strataone_platform: {spec.platform.type.value}
        strataone_hardware_provider: {spec.hardware.vendor}
"""

    def _ansible_playbook(self, spec: SiteSpec) -> str:
        return f"""---
- name: StrataOne deployment handoff for {spec.site.name}
  hosts: strataone_nodes
  gather_facts: false
  tasks:
    - name: Validate StrataOne desired-state handoff
      ansible.builtin.debug:
        msg: "Review provider-specific deployment tasks before live execution."
"""
